# Generated by Django 4.0.4 on 2022-05-05 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymization', '0002_itprofile_bankprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='sharedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('fathers_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('mobile_no', models.IntegerField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=100)),
                ('account_no', models.IntegerField()),
                ('account_type', models.CharField(max_length=50)),
                ('pan_no', models.CharField(max_length=50)),
                ('aadhar_no', models.IntegerField()),
                ('bank_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymization.bankuser')),
                ('it_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymization.itprofile')),
            ],
        ),
    ]
