# Generated by Django 4.0.4 on 2022-05-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymization', '0003_shareddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddata',
            name='it_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
