# Generated by Django 4.0.4 on 2022-05-05 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymization', '0004_shareddata_it_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddata',
            name='it_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
