# Generated by Django 4.0.4 on 2022-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymization', '0007_itname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddata',
            name='dob',
            field=models.CharField(max_length=200),
        ),
    ]
