# Generated by Django 4.0.4 on 2022-05-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymization', '0009_alter_shareddata_aadhar_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareddata',
            old_name='bank_user',
            new_name='bankUser',
        ),
    ]
