# Generated by Django 4.0.4 on 2022-05-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymization', '0010_rename_bank_user_shareddata_bankuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareddata',
            old_name='bankUser',
            new_name='bank_user',
        ),
    ]
