# Generated by Django 4.0.4 on 2022-05-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymization', '0011_rename_bankuser_shareddata_bank_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddata',
            name='bank_man',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anonymization.bankprofile'),
            preserve_default=False,
        ),
    ]
