# Generated by Django 4.0.4 on 2022-05-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymization', '0012_shareddata_bank_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddata',
            name='bank_man_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
