# Generated by Django 4.0.4 on 2022-05-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymization', '0013_shareddata_bank_man_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='balance',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shareddata',
            name='balance',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='aadhar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='account_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
