# Generated by Django 4.0.4 on 2022-05-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymization', '0014_bankuser_balance_shareddata_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_bank_man',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_it_man',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
