# Generated by Django 4.0.4 on 2022-05-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymization', '0015_remove_user_is_bank_man_remove_user_is_it_man_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankprofile',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='itprofile',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
